language: php
php:
- 7.4
env:
  global:
    - XDEBUG_MODE=coverage
before_script:
- composer self-update
- composer install --no-interaction
script:
- ./vendor/bin/phpunit --coverage-text
- ./vendor/bin/phpunit --coverage-clover=coverage.clover
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  email: royopa@gmail.com
matrix:
  fast_finish: true
